### ISSUE TITLE
Github API rate limit exceeded 

### ISSUE THREAD

**Issue by YahyaOukharta** [Ray0Emma/Get-Your-Repos#1]
Getting these error on the console:
```
{
 message: 'API rate limit exceeded for 197.230.240.146. (But …t. Check out the documentation for more details.)', 
 documentation_url: 'https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting'
}
```

**Comment by Ray0Emma** [comment]
Hi @YahyaOukharta! thanks for reporting this issue.
Can you explain more about what were you trying to do before getting this error? 

But in all cases what you have to know is :

The Search API has a custom rate limit. For requests using Basic Authentication, OAuth, or client ID and secret, you can make up to 30 requests per minute. For unauthenticated requests (which is our case), the rate limit allows you to make up to 10 requests per minute.

To be honest this repo was only for trying some ideas. so that I didn't work on increasing the API Rate limit.

**Comment by YahyaOukharta** [comment]
Hello,
The error occured on my first attempt, after i wrote my username on the app,
I see how this project was just an experiment, and it's really good,
Goodluck!
